
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: symfony_felina_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      # Mapea el puerto 3307 del host al 3306 del contenedor
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_felina_phpmyadmin
    restart: unless-stopped
    environment:
      # PMA_HOST apunta al nombre del servicio de base de datos (db)
      PMA_HOST: db
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    ports:
      # Mapea el puerto 8081 del host al 80 del contenedor
      - "8081:80"
    depends_on:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###


